# Generated by Django 2.2.13 on 2023-08-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_post_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_post', to='accounts.Column'),
        ),
    ]
